# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-29 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subredditcontent',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='subreddit_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subreddit_content', to='reddit.SubredditContent'),
        ),
    ]
