# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subredditcontent',
            name='subs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='reddit.Subreddit'),
        ),
    ]
