# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_auto_20180526_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subredditcontent',
            name='subs',
        ),
        migrations.AddField(
            model_name='subredditcontent',
            name='subreddit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subreddit', to='reddit.Subreddit'),
        ),
    ]
