# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-29 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_auto_20180729_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subreddit_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='reddit.SubredditContent'),
        ),
    ]
