# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-29 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_auto_20180729_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subreddit_content',
        ),
        migrations.AddField(
            model_name='subredditcontent',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentss', to='reddit.Comment'),
        ),
    ]
