# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-02 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0006_auto_20180526_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subredditcontent',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='reddit.Comment'),
        ),
    ]
