# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-02 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0007_auto_20180602_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subredditcontent',
            name='subreddit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subreddit_content', to='reddit.Subreddit'),
        ),
    ]
